# Generated by Django 2.2.3 on 2019-07-27 11:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190727_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default='Country', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(default='County', max_length=150),
        ),
    ]
