# Generated by Django 2.2.3 on 2019-07-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190727_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
