# Generated by Django 2.2.3 on 2019-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(default='https//:'),
        ),
    ]
