# Generated by Django 2.2.4 on 2019-09-02 10:22

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmusic',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', null=True, upload_to='media/songs/'),
        ),
    ]
