# Generated by Django 2.2.4 on 2019-09-03 11:36

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_auto_20190902_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmusic',
            name='audio_file',
            field=audiofield.fields.AudioField(default='', help_text='Allowed type - .mp3, .wav, .ogg', upload_to='media/songs/'),
        ),
    ]
