# Generated by Django 2.2.4 on 2019-09-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0003_auto_20190903_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmusic',
            name='composer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
