# Generated by Django 2.2.4 on 2019-09-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0004_uploadmusic_composer'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmusic',
            name='allow_listening',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadmusic',
            name='genre',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
