# Generated by Django 2.2.4 on 2019-09-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0006_auto_20190922_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmusic',
            old_name='genre',
            new_name='genres',
        ),
    ]
