# Generated by Django 2.2.4 on 2019-09-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0007_auto_20190922_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmusic',
            name='genres',
        ),
    ]
