# Generated by Django 2.2.4 on 2019-09-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0008_remove_uploadmusic_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmusic',
            name='genres',
            field=models.CharField(default='world music', max_length=30),
        ),
    ]
