# Generated by Django 2.2.4 on 2019-09-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0009_uploadmusic_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmusic',
            name='genres',
        ),
        migrations.AddField(
            model_name='uploadmusic',
            name='genre',
            field=models.CharField(choices=[(1, 'Blues'), (2, 'Raggae'), (3, 'Rock lover'), (4, 'Rock Jazz'), (5, 'Slow Jam'), (6, 'Jazz'), (7, 'Samba'), (8, 'Afro Jazz')], default='select a genre', max_length=30),
        ),
    ]
